version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      # Set Ruby version
     - run:
          name: Bundle Install
          command: |
            sudo gem install bundler -v 1.15.4 # <-- wut
            bundle install --path vendor/bundle --jobs 4 --retry 3
      - run:
          name: Install cocoapods
          command: gem install cocoapods --verbose
      - run:
          name: Install pods
          command: cd framework; pod install
      - run:
          name: Run Tests
          command: cd framework; fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: VGSFramework

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
