version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      # - run:
      #     name: Set Ruby Version
      #     command: echo "ruby-2.6.3" > ~/.ruby-version
      # - run:
      #     name: Configure Bundler
      #     command: |
      #       echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
      #       source $BASH_ENV
      #       sudo gem install bundler
      - run:
          name: Install cocoapods
          command: sudo gem install cocoapods --verbose
      - run:
          name: Install pods
          command: cd framework; pod install
      - run:
          name: Run Tests
          command: cd framework; fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: VGSFramework

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
