version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      # - run:
      #     name: Fetch CocoaPods Specs
      #     command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      
      # Install CocoaPods
  - run:
      name: Install CocoaPods
      command: pod install

  # Set Ruby version
  - run:
      name: Set Ruby Version
      command:  echo "ruby-2.4" > ~/.ruby-version
      
      - run:
          name: Install cocoapods
          command: gem install cocoapods --verbose
      - run:
          name: Install pods
          command: cd framework; pod install
      - run:
          name: Run Tests
          command: cd framework; fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: VGSFramework

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
